"use client";

/**
 * Cal, out loud.
 *
 * The mp3s in public/vo are generated by scripts/make-vo.py and shipped with
 * the game, so there is no key, no network and no speech API at run time.
 *
 * One channel, on purpose. Cal is one man in one room and he does not talk over
 * himself — starting a line cuts whatever was playing. That also means a player
 * who clicks through the case file fast never ends up with four overlapping
 * takes, which is the usual way game narration falls apart.
 *
 * Nothing here plays before the player has clicked something. Every call site is
 * downstream of a real gesture (the START button, a page turn, hitting SAVE in
 * the editor), which is what browsers require and also what stops the game
 * talking at somebody who has not looked at it yet.
 */

const MUTE_KEY = "tinfoil-keys:muted";

let el: HTMLAudioElement | null = null;
let muted = false;
let ready = false;

/** Cached elements so a repeated line does not re-download. */
const cache = new Map<string, HTMLAudioElement>();

/** Everything that wants to know when the mute button is pressed. */
const listeners = new Set<(m: boolean) => void>();

function init() {
  if (ready || typeof window === "undefined") return;
  ready = true;
  try {
    muted = localStorage.getItem(MUTE_KEY) === "1";
  } catch {
    /* private mode: just start unmuted */
  }
}

function audio(id: string): HTMLAudioElement {
  let a = cache.get(id);
  if (!a) {
    a = new Audio(`/vo/${id}.mp3`);
    a.preload = "auto";
    cache.set(id, a);
  }
  return a;
}

/** Play one line, cutting anything already running. */
export function say(id: string) {
  init();
  if (muted || typeof window === "undefined") return;
  stop();
  const a = audio(id);
  a.currentTime = 0;
  el = a;
  // A blocked play is not an error worth showing anyone — it means the browser
  // has not seen a gesture yet, and the next line will work.
  void a.play().catch(() => {});
}

/** Pick one of several takes, so a repeated beat does not sound like a robot. */
export function sayOneOf(ids: readonly string[]) {
  if (ids.length) say(ids[Math.floor(Math.random() * ids.length)]);
}

export function stop() {
  if (!el) return;
  el.pause();
  el.currentTime = 0;
  el = null;
}

export function isMuted() {
  init();
  return muted;
}

export function setMuted(next: boolean) {
  init();
  muted = next;
  if (next) stop();
  try {
    localStorage.setItem(MUTE_KEY, next ? "1" : "0");
  } catch {
    /* nothing to do */
  }
  listeners.forEach((fn) => fn(next));
}

/** Returns an unsubscribe function, shaped for useEffect's cleanup slot. */
export function onMuteChange(fn: (m: boolean) => void): () => void {
  listeners.add(fn);
  return () => {
    listeners.delete(fn);
  };
}

/**
 * Pull the short reaction lines down early, so the first "no, that is nothing"
 * lands the instant it is earned instead of a beat late. Called once the player
 * has committed to playing.
 */
export function warm() {
  init();
  [...MISS, ...PIN, "not-yet", "accuse-lead", "accuse-short"].forEach((id) => audio(id).load());
}

// --- the lines, named rather than typed as loose strings --------------------

const MISS = ["miss-1", "miss-2"] as const;
const PIN = ["pin-1", "pin-2"] as const;

/**
 * Cal introduces himself.
 *
 * Fires from two places — the START button on the how-to card, and the first
 * time the player takes hold of the mouse — because the how-to card only ever
 * appears once. Before this, anybody coming back for a second go never heard
 * the intro at all.
 *
 * Guarded so it plays at most once per page load no matter which one wins.
 */
let introPlayed = false;
export function voIntro() {
  if (introPlayed) return;
  introPlayed = true;
  say("intro");
}

/** A page of the case file, 1-based. */
export const voStory = (page: number) => say(`story-${page}`);

/** The clue you just uncovered by drawing on the right thing. */
export const voClue = (hotspotId: string) => say(`clue-${hotspotId}`);

/** You drew, but not on anything. Looking is free and he says so. */
export const voMiss = () => sayOneOf(MISS);

export const voPin = () => sayOneOf(PIN);

/** Enough of the yard is proved. Cal stops caring about it and starts on Luis. */
export const voYardDirty = () => say("yard-dirty");

/** Tried to name somebody before working out who the man in the photos is. */
export const voNotYet = () => say("not-yet");

/** Cal asking for the sentence. */
export const voAccuseLead = () => say("accuse-lead");

/** Said it, and some of it does not hold. Never says which part. */
export const voShort = () => say("accuse-short");

/** WASTED or CASE CRACKED. */
export const voEnding = (wasted: boolean) => say(wasted ? "lost" : "win");
