/**
 * Downloads the CC0 models the room uses, from Poly Haven.
 *
 * Everything here is CC0 (public domain) — checked on polyhaven.com/license:
 * "You can use our assets for any purpose, including commercial work. You do
 * not need to give credit." We credit anyway, in CREDITS.md, because the
 * challenge asks us to show we have the rights to every asset we ship.
 *
 * Always the 1k glTF, never 2k or 4k. A judge clicking a link should not wait
 * on a 60MB download to look at a corkboard.
 *
 * Run: node scripts/fetch-models.mjs
 */
import { mkdir, writeFile } from "node:fs/promises";
import { existsSync, statSync } from "node:fs";
import { dirname } from "node:path";

/** Chosen by eye from the contact sheets in art-raw/, not by filename. */
const WANTED = [
  ["ceiling_fan", "the fan overhead"],
  ["drawer_cabinet", "modern drawer unit on the left wall"],
  ["ClassicNightstand_01", "side table by the window"],
  ["chinese_console_table", "the long table under the board"],
  ["cardboard_box_01", "the box the photos come out of"],
  ["cassette_player", "Cal's scanner — he listens to Coast Guard traffic"],
  ["CheeseBox_01", "wooden crate, floor clutter"],
  ["magnifying_glass_01", "on the desk, because of course it is"],
  ["wine_bottles_01", "bottles on the table and the side table"],
  ["plastic_monobloc_chair_01", "white chair out on the balcony"],
  ["desk_lamp_arm_01", "the lamp that lights the board"],
  ["plastic_crate_02", "storage crate on the shelving"],
];

const OUT = "public/models";
const credits = [];
let grandTotal = 0;

for (const [id, why] of WANTED) {
  const [files, info] = await Promise.all([
    fetch(`https://api.polyhaven.com/files/${id}`).then((r) => r.json()),
    fetch(`https://api.polyhaven.com/info/${id}`).then((r) => r.json()),
  ]);

  const g = files?.gltf?.["1k"]?.gltf;
  if (!g) {
    console.error(`${id}: no 1k glTF, skipped`);
    continue;
  }

  const mainName = g.url.split("/").pop();
  const targets = [[`${OUT}/${id}/${mainName}`, g.url]];
  for (const [rel, f] of Object.entries(g.include || {})) {
    targets.push([`${OUT}/${id}/${rel}`, f.url]);
  }

  let bytes = 0;
  for (const [path, url] of targets) {
    if (existsSync(path)) {
      bytes += statSync(path).size;
      continue;
    }
    const res = await fetch(url);
    if (!res.ok) throw new Error(`${id}: ${res.status} on ${url}`);
    const buf = Buffer.from(await res.arrayBuffer());
    await mkdir(dirname(path), { recursive: true });
    await writeFile(path, buf);
    bytes += buf.length;
  }

  grandTotal += bytes;
  const authors = Object.keys(info?.authors || {}).join(", ") || "Poly Haven";
  credits.push({ id, name: info?.name || id, authors, why, path: `${OUT}/${id}/${mainName}`, kb: Math.round(bytes / 1024) });
  console.log(`${id.padEnd(24)} ${(bytes / 1024).toFixed(0).padStart(6)}kb  ${mainName}`);
}

console.log(`\ntotal ${(grandTotal / 1024 / 1024).toFixed(2)}MB across ${credits.length} models`);

const md = `# Credits

Every third-party asset in this project, and where it came from.

## 3D models — Poly Haven

All models below are **CC0 (public domain)**. From https://polyhaven.com/license:

> All assets are all licensed as CC0, which is effectively Public Domain [...]
> You can use our assets for any purpose, including commercial work.
> You do not need to give credit or attribution when using them.

Credit is given anyway.

| asset | author | used for | size |
|---|---|---|---|
${credits.map((c) => `| [${c.name}](https://polyhaven.com/a/${c.id}) | ${c.authors} | ${c.why} | ${c.kb}kb |`).join("\n")}

## Textures

The cork board and the view through the window are generated by
\`scripts/make-room-textures.mjs\` in this repo. They are ours.

## Photographs

All 14 case photos are AI-generated for this project. They are ours. No real
place, business or person appears in them.

## Not affiliated

Unofficial fan project. Not affiliated with or endorsed by Rockstar Games or
Take-Two Interactive. No Rockstar assets are used anywhere in this repository.
`;

await writeFile("CREDITS.md", md);
console.log("wrote CREDITS.md");
