"""
Masters Cal's voice lines for the game.

The lines are generated by hand in ElevenLabs (Eleven v3, the "Michael - Gruff
and Serious" voice) from the script that scripts/make-vo-lines.py writes out.
What comes back is good, but it comes back at whatever level each take happened
to land on — measured across the 24 files that was a 13 dB spread, from -14 dB
to -27 dB. In a game that means a whispered clue right after a loud one is
simply not audible, and the player thinks the sound is broken.

So this does two things and deliberately nothing else:

  - **evens the levels.** loudnorm measures each file as a whole and applies one
    gain to it, so the quiet parts *inside* a take stay quiet relative to the
    rest of that take. The performance survives; only the file-to-file jumps go.
  - **shrinks them.** 128 kbps for one mono voice is more than speech needs.

No tape effect, no pitch shift, no hiss. An earlier version of this game used a
local model that needed all of that to sound like anything; this does not, and
processing good audio for the sake of it only makes it worse.

Originals are copied to art-raw/vo-el/ before anything is touched, so this can
be run again, or undone, without regenerating a single credit's worth of speech.

Run: python scripts/process-vo.py
"""

from __future__ import annotations

import hashlib
import json
import pathlib
import shutil
import subprocess
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
VO = ROOT / "public" / "vo"
RAW = ROOT / "art-raw" / "vo-el"
LINES = ROOT / "art-raw" / "vo-lines.json"

TARGET_LUFS = -18
BITRATE = "96k"


def probe(path: pathlib.Path) -> float:
    out = subprocess.run(
        ["ffprobe", "-v", "error", "-show_entries", "format=duration",
         "-of", "default=nw=1:nk=1", str(path)],
        check=True, capture_output=True, text=True,
    )
    return float(out.stdout.strip())


def master(src: pathlib.Path, dst: pathlib.Path) -> None:
    subprocess.run(
        [
            "ffmpeg", "-y", "-loglevel", "error", "-i", str(src),
            # 80 Hz is below anything in a human voice, so this only takes out
            # rumble and room thump.
            "-af", f"highpass=f=80,loudnorm=I={TARGET_LUFS}:TP=-1.5:LRA=11",
            "-c:a", "libmp3lame", "-b:a", BITRATE, "-ac", "1", "-ar", "44100",
            str(dst),
        ],
        check=True,
    )


def main() -> None:
    if not LINES.exists():
        sys.exit("run scripts/make-vo-lines.py first — it writes art-raw/vo-lines.json")
    lines = json.loads(LINES.read_text(encoding="utf-8"))

    have = {p.stem for p in VO.glob("*.mp3")}
    missing = sorted(set(lines) - have)
    if missing:
        sys.exit(f"no audio for: {', '.join(missing)}")
    extra = sorted(have - set(lines))
    if extra:
        print(f"note: not in the script, left alone: {', '.join(extra)}")

    # --- back up the raw takes, carefully ----------------------------------
    #
    # This used to be `if not keep.exists(): copy`, and that destroyed twelve
    # newly recorded lines. A previous case left backups behind under the same
    # ids, so the fresh downloads were never backed up — and then mastering ran
    # FROM those stale backups, straight over the new audio.
    #
    # The rule now: a file in public/vo is a fresh take unless it is byte for
    # byte something this script produced. We remember the hash of every file we
    # write, so a re-run is safely idempotent and a new download always wins.
    RAW.mkdir(parents=True, exist_ok=True)
    stamp_file = RAW / ".mastered.json"
    try:
        stamp = json.loads(stamp_file.read_text(encoding="utf-8"))
    except Exception:
        stamp = {}

    def digest(path: pathlib.Path) -> str:
        return hashlib.md5(path.read_bytes()).hexdigest()

    fresh = 0
    for key in lines:
        src = VO / f"{key}.mp3"
        keep = RAW / f"{key}.mp3"
        already_ours = keep.exists() and stamp.get(key) == digest(src)
        if not already_ours:
            shutil.copy2(src, keep)
            fresh += 1
    print(f"originals safe in {RAW.relative_to(ROOT)}  ({fresh} new take(s) backed up)")

    manifest: dict[str, dict] = {}
    before = after = 0
    for i, key in enumerate(lines, start=1):
        src = RAW / f"{key}.mp3"
        dst = VO / f"{key}.mp3"
        before += src.stat().st_size
        master(src, dst)
        after += dst.stat().st_size
        ms = round(probe(dst) * 1000)
        stamp[key] = hashlib.md5(dst.read_bytes()).hexdigest()
        manifest[key] = {"ms": ms, "text": lines[key]}
        print(f"  [{i:2}/{len(lines)}] {key:<16} {ms / 1000:5.1f}s")

    stamp_file.write_text(json.dumps(stamp, indent=1) + chr(10), encoding="utf-8")
    (VO / "manifest.json").write_text(
        json.dumps(manifest, indent=1, ensure_ascii=False) + "\n", encoding="utf-8"
    )

    secs = sum(m["ms"] for m in manifest.values()) / 1000
    print(
        f"\n{len(manifest)} lines · {secs / 60:.1f} min of Cal · "
        f"{before / 1024 / 1024:.1f} MB -> {after / 1024 / 1024:.1f} MB"
    )


if __name__ == "__main__":
    main()
